// Generated by `pnpm contracts:generate` from packages/contracts/schema/. Do not edit.
// `pnpm contracts:check` fails when this file and the schema disagree.

/** The protocol version this build speaks. */
export const PROTOCOL_VERSION = 1;

/** Every `type` the generated frames cover, for exhaustiveness at the call site. */
export const FRAME_TYPES = [
  'connection.ready',
  'connection.authenticate',
  'connection.reauthenticate',
  'error',
] as const;

/** Shape shared by every frame, in both directions. See docs/architecture/shared/05-websocket-protocol.md. */
export interface Envelope {
  /** Protocol version. Adding an optional field or a new event does not change it; removing a field, renaming a type or changing a meaning does. */
  readonly v: 1;
  /** ULID unique to this frame. */
  readonly id: string;
  /** What the frame is. `request` travels server to client and demands an answer — that is the case the whole protocol is designed around. */
  readonly kind: 'command' | 'event' | 'request' | 'response' | 'ack' | 'error';
  /** What the frame is, within its kind. */
  readonly type: string;
  /** ISO 8601 instant, in UTC. */
  readonly ts: string;
  /** Correlates this frame with the server logs of the same operation. */
  readonly traceId?: string;
  /** `id` of the frame that caused this one. */
  readonly correlationId?: string;
  /** Monotonic per session, on events only. This is what makes replay after a reconnect possible. */
  readonly seq?: number;
  /** Contents, defined per `type`. */
  readonly payload?: Readonly<Record<string, unknown>>;
}

/** What this server will accept, so the client does not have to discover it by being refused. */
export interface ConnectionReadyPayloadLimits {
  readonly maxFrameBytes: number;
  readonly replayBufferSize: number;
}

/** Answer to a successful handshake. An ack, not an event: it acknowledges the command that caused it. */
export interface ConnectionReadyPayload {
  readonly connectionId: string;
  readonly serverVersion: string;
  /** What this server will accept, so the client does not have to discover it by being refused. */
  readonly limits: ConnectionReadyPayloadLimits;
}

/** Who is connecting, for diagnostics and for the deprecation window. */
export interface ConnectionAuthenticatePayloadClient {
  readonly kind: 'web' | 'mobile';
  readonly version: string;
}

/** Opens the connection. Without it inside 5 seconds the server closes with 4401. */
export interface ConnectionAuthenticatePayload {
  /** OIDC access token. In the frame body, never in the query string — a query string leaks into proxy logs. */
  readonly token: string;
  /** Language of this connection, not of the user. */
  readonly locale: 'en' | 'pt-BR';
  /** Who is connecting, for diagnostics and for the deprecation window. */
  readonly client: ConnectionAuthenticatePayloadClient;
}

/** Renews the credential without reopening the socket. An access token expiring on an open connection does not drop it; failing to renew within the 60 s grace period closes it with 4401. */
export interface ConnectionReauthenticatePayload {
  /** The renewed OIDC access token. */
  readonly token: string;
}

export interface ErrorPayloadDetailsItem {
  readonly field: string;
  readonly rule: string;
}

/** The error envelope, identical to the HTTP one. See docs/architecture/shared/04-errors-and-http.md. */
export interface ErrorPayload {
  /** Stable, for client logic. Changing one is a breaking change. */
  readonly code: string;
  /** For display. The client translates it — the server never sends prose. */
  readonly messageKey: string;
  /** Interpolation values for the message key. */
  readonly params?: Readonly<Record<string, unknown>>;
  /** Lets a user report the problem and someone find it in the log. */
  readonly traceId: string;
  /** Validation only: every invalid field, not just the first. */
  readonly details?: readonly ErrorPayloadDetailsItem[];
}

/** Whether `value` carries every required field of {@link Envelope}. Unknown fields are accepted. */
export function isEnvelope(value: unknown): value is Envelope {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const record = value as Readonly<Record<string, unknown>>;

  return !(
    record['v'] !== 1 ||
    typeof record['id'] !== 'string' ||
    typeof record['kind'] !== 'string' ||
    typeof record['type'] !== 'string' ||
    typeof record['ts'] !== 'string'
  );
}

/** Whether `value` carries every required field of {@link ConnectionReadyPayloadLimits}. Unknown fields are accepted. */
export function isConnectionReadyPayloadLimits(value: unknown): value is ConnectionReadyPayloadLimits {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const record = value as Readonly<Record<string, unknown>>;

  return !(
    typeof record['maxFrameBytes'] !== 'number' ||
    typeof record['replayBufferSize'] !== 'number'
  );
}

/** Whether `value` carries every required field of {@link ConnectionReadyPayload}. Unknown fields are accepted. */
export function isConnectionReadyPayload(value: unknown): value is ConnectionReadyPayload {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const record = value as Readonly<Record<string, unknown>>;

  return !(
    typeof record['connectionId'] !== 'string' ||
    typeof record['serverVersion'] !== 'string' ||
    !isConnectionReadyPayloadLimits(record['limits'])
  );
}

/** Whether `value` carries every required field of {@link ConnectionAuthenticatePayloadClient}. Unknown fields are accepted. */
export function isConnectionAuthenticatePayloadClient(value: unknown): value is ConnectionAuthenticatePayloadClient {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const record = value as Readonly<Record<string, unknown>>;

  return !(
    typeof record['kind'] !== 'string' ||
    typeof record['version'] !== 'string'
  );
}

/** Whether `value` carries every required field of {@link ConnectionAuthenticatePayload}. Unknown fields are accepted. */
export function isConnectionAuthenticatePayload(value: unknown): value is ConnectionAuthenticatePayload {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const record = value as Readonly<Record<string, unknown>>;

  return !(
    typeof record['token'] !== 'string' ||
    typeof record['locale'] !== 'string' ||
    !isConnectionAuthenticatePayloadClient(record['client'])
  );
}

/** Whether `value` carries every required field of {@link ConnectionReauthenticatePayload}. Unknown fields are accepted. */
export function isConnectionReauthenticatePayload(value: unknown): value is ConnectionReauthenticatePayload {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const record = value as Readonly<Record<string, unknown>>;

  return !(
    typeof record['token'] !== 'string'
  );
}

/** Whether `value` carries every required field of {@link ErrorPayloadDetailsItem}. Unknown fields are accepted. */
export function isErrorPayloadDetailsItem(value: unknown): value is ErrorPayloadDetailsItem {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const record = value as Readonly<Record<string, unknown>>;

  return !(
    typeof record['field'] !== 'string' ||
    typeof record['rule'] !== 'string'
  );
}

/** Whether `value` carries every required field of {@link ErrorPayload}. Unknown fields are accepted. */
export function isErrorPayload(value: unknown): value is ErrorPayload {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const record = value as Readonly<Record<string, unknown>>;

  return !(
    typeof record['code'] !== 'string' ||
    typeof record['messageKey'] !== 'string' ||
    typeof record['traceId'] !== 'string'
  );
}

/** Answer to a successful handshake. An ack, not an event: it acknowledges the command that caused it. */
export interface ConnectionReadyFrame extends Omit<Envelope, 'kind' | 'type' | 'payload'> {
  readonly kind: 'ack';
  readonly type: 'connection.ready';
  readonly payload: ConnectionReadyPayload;
}

/** Whether `value` is a {@link ConnectionReadyFrame}. */
export function isConnectionReadyFrame(value: unknown): value is ConnectionReadyFrame {
  if (!isEnvelope(value)) {
    return false;
  }

  return (
    value.kind === 'ack' &&
    value.type === 'connection.ready' &&
    isConnectionReadyPayload(value.payload)
  );
}

/** Opens the connection. Without it inside 5 seconds the server closes with 4401. */
export interface ConnectionAuthenticateFrame extends Omit<Envelope, 'kind' | 'type' | 'payload'> {
  readonly kind: 'command';
  readonly type: 'connection.authenticate';
  readonly payload: ConnectionAuthenticatePayload;
}

/** Whether `value` is a {@link ConnectionAuthenticateFrame}. */
export function isConnectionAuthenticateFrame(value: unknown): value is ConnectionAuthenticateFrame {
  if (!isEnvelope(value)) {
    return false;
  }

  return (
    value.kind === 'command' &&
    value.type === 'connection.authenticate' &&
    isConnectionAuthenticatePayload(value.payload)
  );
}

/** Renews the credential without reopening the socket. An access token expiring on an open connection does not drop it; failing to renew within the 60 s grace period closes it with 4401. */
export interface ConnectionReauthenticateFrame extends Omit<Envelope, 'kind' | 'type' | 'payload'> {
  readonly kind: 'command';
  readonly type: 'connection.reauthenticate';
  readonly payload: ConnectionReauthenticatePayload;
}

/** Whether `value` is a {@link ConnectionReauthenticateFrame}. */
export function isConnectionReauthenticateFrame(value: unknown): value is ConnectionReauthenticateFrame {
  if (!isEnvelope(value)) {
    return false;
  }

  return (
    value.kind === 'command' &&
    value.type === 'connection.reauthenticate' &&
    isConnectionReauthenticatePayload(value.payload)
  );
}

/** The error envelope, identical to the HTTP one. See docs/architecture/shared/04-errors-and-http.md. */
export interface ErrorFrame extends Omit<Envelope, 'kind' | 'type' | 'payload'> {
  readonly kind: 'error';
  readonly type: 'error';
  readonly payload: ErrorPayload;
}

/** Whether `value` is a {@link ErrorFrame}. */
export function isErrorFrame(value: unknown): value is ErrorFrame {
  if (!isEnvelope(value)) {
    return false;
  }

  return (
    value.kind === 'error' &&
    value.type === 'error' &&
    isErrorPayload(value.payload)
  );
}
