/**
 * The pieces both contract emitters need.
 *
 * They exist here rather than twice because that is precisely what the duplication gate is for:
 * a banner that says one thing in the TypeScript and another in the Dart is how the two halves
 * of a generated contract start drifting.
 */

/** Header put on every generated file, whichever language it is in. */
export const BANNER = [
  '// Generated by `pnpm contracts:generate` from packages/contracts/schema/. Do not edit.',
  '// `pnpm contracts:check` fails when this file and the schema disagree.',
].join('\n');

/**
 * A documentation comment, in the style of the target language.
 *
 * @param {string} description empty means no comment at all, not an empty one
 * @param {string} indent
 * @param {'block' | 'line'} style `block` is TypeScript's `/** … *\u002f`, `line` is Dart's `///`
 * @returns {string[]}
 */
export function docComment(description, indent, style) {
  if (description === '') {
    return [];
  }

  return [style === 'block' ? `${indent}/** ${description} */` : `${indent}/// ${description}`];
}
