// Generated by `pnpm contracts:generate` from packages/contracts/schema/. Do not edit.
// `pnpm contracts:check` fails when this file and the schema disagree.

// dart format off

/// The protocol version this build speaks.
const int protocolVersion = 1;

/// Every frame `type` the classes below cover.
const List<String> frameTypes = <String>[
  'command.accepted',
  'connection.ready',
  'session.attached',
  'workspace.watching',
  'connection.authenticate',
  'connection.reauthenticate',
  'diag.ping',
  'permission.extend',
  'session.attach',
  'session.cancelQueuedPrompt',
  'session.close',
  'session.detach',
  'session.interrupt',
  'session.prompt',
  'session.rejectChange',
  'session.rewindFiles',
  'session.setLocale',
  'session.setModel',
  'session.setPermissionMode',
  'session.start',
  'workspace.unwatch',
  'workspace.watch',
  'diag.pong',
  'error',
  'message.completed',
  'message.delta',
  'permission.extended',
  'permission.requested',
  'permission.resolved',
  'prompt.dequeued',
  'prompt.queued',
  'session.closed',
  'session.compacted',
  'session.rewound',
  'session.started',
  'session.statusChanged',
  'tool.completed',
  'tool.progress',
  'tool.started',
  'turn.completed',
  'workspace.filesChanged',
  'workspace.watchStopped',
  'permission.resolve',
];

/// `kind` of a command.accepted frame.
const String commandAcceptedKind = 'ack';

/// `type` of a command.accepted frame.
const String commandAcceptedType = 'command.accepted';

/// `kind` of a connection.ready frame.
const String connectionReadyKind = 'ack';

/// `type` of a connection.ready frame.
const String connectionReadyType = 'connection.ready';

/// `kind` of a session.attached frame.
const String sessionAttachedKind = 'ack';

/// `type` of a session.attached frame.
const String sessionAttachedType = 'session.attached';

/// `kind` of a workspace.watching frame.
const String workspaceWatchingKind = 'ack';

/// `type` of a workspace.watching frame.
const String workspaceWatchingType = 'workspace.watching';

/// `kind` of a connection.authenticate frame.
const String connectionAuthenticateKind = 'command';

/// `type` of a connection.authenticate frame.
const String connectionAuthenticateType = 'connection.authenticate';

/// `kind` of a connection.reauthenticate frame.
const String connectionReauthenticateKind = 'command';

/// `type` of a connection.reauthenticate frame.
const String connectionReauthenticateType = 'connection.reauthenticate';

/// `kind` of a diag.ping frame.
const String diagPingKind = 'command';

/// `type` of a diag.ping frame.
const String diagPingType = 'diag.ping';

/// `kind` of a permission.extend frame.
const String permissionExtendKind = 'command';

/// `type` of a permission.extend frame.
const String permissionExtendType = 'permission.extend';

/// `kind` of a session.attach frame.
const String sessionAttachKind = 'command';

/// `type` of a session.attach frame.
const String sessionAttachType = 'session.attach';

/// `kind` of a session.cancelQueuedPrompt frame.
const String sessionCancelQueuedPromptKind = 'command';

/// `type` of a session.cancelQueuedPrompt frame.
const String sessionCancelQueuedPromptType = 'session.cancelQueuedPrompt';

/// `kind` of a session.close frame.
const String sessionCloseKind = 'command';

/// `type` of a session.close frame.
const String sessionCloseType = 'session.close';

/// `kind` of a session.detach frame.
const String sessionDetachKind = 'command';

/// `type` of a session.detach frame.
const String sessionDetachType = 'session.detach';

/// `kind` of a session.interrupt frame.
const String sessionInterruptKind = 'command';

/// `type` of a session.interrupt frame.
const String sessionInterruptType = 'session.interrupt';

/// `kind` of a session.prompt frame.
const String sessionPromptKind = 'command';

/// `type` of a session.prompt frame.
const String sessionPromptType = 'session.prompt';

/// `kind` of a session.rejectChange frame.
const String sessionRejectChangeKind = 'command';

/// `type` of a session.rejectChange frame.
const String sessionRejectChangeType = 'session.rejectChange';

/// `kind` of a session.rewindFiles frame.
const String sessionRewindFilesKind = 'command';

/// `type` of a session.rewindFiles frame.
const String sessionRewindFilesType = 'session.rewindFiles';

/// `kind` of a session.setLocale frame.
const String sessionSetLocaleKind = 'command';

/// `type` of a session.setLocale frame.
const String sessionSetLocaleType = 'session.setLocale';

/// `kind` of a session.setModel frame.
const String sessionSetModelKind = 'command';

/// `type` of a session.setModel frame.
const String sessionSetModelType = 'session.setModel';

/// `kind` of a session.setPermissionMode frame.
const String sessionSetPermissionModeKind = 'command';

/// `type` of a session.setPermissionMode frame.
const String sessionSetPermissionModeType = 'session.setPermissionMode';

/// `kind` of a session.start frame.
const String sessionStartKind = 'command';

/// `type` of a session.start frame.
const String sessionStartType = 'session.start';

/// `kind` of a workspace.unwatch frame.
const String workspaceUnwatchKind = 'command';

/// `type` of a workspace.unwatch frame.
const String workspaceUnwatchType = 'workspace.unwatch';

/// `kind` of a workspace.watch frame.
const String workspaceWatchKind = 'command';

/// `type` of a workspace.watch frame.
const String workspaceWatchType = 'workspace.watch';

/// `kind` of a diag.pong frame.
const String diagPongKind = 'event';

/// `type` of a diag.pong frame.
const String diagPongType = 'diag.pong';

/// `kind` of a error frame.
const String errorKind = 'error';

/// `type` of a error frame.
const String errorType = 'error';

/// `kind` of a message.completed frame.
const String messageCompletedKind = 'event';

/// `type` of a message.completed frame.
const String messageCompletedType = 'message.completed';

/// `kind` of a message.delta frame.
const String messageDeltaKind = 'event';

/// `type` of a message.delta frame.
const String messageDeltaType = 'message.delta';

/// `kind` of a permission.extended frame.
const String permissionExtendedKind = 'event';

/// `type` of a permission.extended frame.
const String permissionExtendedType = 'permission.extended';

/// `kind` of a permission.requested frame.
const String permissionRequestedKind = 'request';

/// `type` of a permission.requested frame.
const String permissionRequestedType = 'permission.requested';

/// `kind` of a permission.resolved frame.
const String permissionResolvedKind = 'event';

/// `type` of a permission.resolved frame.
const String permissionResolvedType = 'permission.resolved';

/// `kind` of a prompt.dequeued frame.
const String promptDequeuedKind = 'event';

/// `type` of a prompt.dequeued frame.
const String promptDequeuedType = 'prompt.dequeued';

/// `kind` of a prompt.queued frame.
const String promptQueuedKind = 'event';

/// `type` of a prompt.queued frame.
const String promptQueuedType = 'prompt.queued';

/// `kind` of a session.closed frame.
const String sessionClosedKind = 'event';

/// `type` of a session.closed frame.
const String sessionClosedType = 'session.closed';

/// `kind` of a session.compacted frame.
const String sessionCompactedKind = 'event';

/// `type` of a session.compacted frame.
const String sessionCompactedType = 'session.compacted';

/// `kind` of a session.rewound frame.
const String sessionRewoundKind = 'event';

/// `type` of a session.rewound frame.
const String sessionRewoundType = 'session.rewound';

/// `kind` of a session.started frame.
const String sessionStartedKind = 'event';

/// `type` of a session.started frame.
const String sessionStartedType = 'session.started';

/// `kind` of a session.statusChanged frame.
const String sessionStatusChangedKind = 'event';

/// `type` of a session.statusChanged frame.
const String sessionStatusChangedType = 'session.statusChanged';

/// `kind` of a tool.completed frame.
const String toolCompletedKind = 'event';

/// `type` of a tool.completed frame.
const String toolCompletedType = 'tool.completed';

/// `kind` of a tool.progress frame.
const String toolProgressKind = 'event';

/// `type` of a tool.progress frame.
const String toolProgressType = 'tool.progress';

/// `kind` of a tool.started frame.
const String toolStartedKind = 'event';

/// `type` of a tool.started frame.
const String toolStartedType = 'tool.started';

/// `kind` of a turn.completed frame.
const String turnCompletedKind = 'event';

/// `type` of a turn.completed frame.
const String turnCompletedType = 'turn.completed';

/// `kind` of a workspace.filesChanged frame.
const String workspaceFilesChangedKind = 'event';

/// `type` of a workspace.filesChanged frame.
const String workspaceFilesChangedType = 'workspace.filesChanged';

/// `kind` of a workspace.watchStopped frame.
const String workspaceWatchStoppedKind = 'event';

/// `type` of a workspace.watchStopped frame.
const String workspaceWatchStoppedType = 'workspace.watchStopped';

/// `kind` of a permission.resolve frame.
const String permissionResolveKind = 'response';

/// `type` of a permission.resolve frame.
const String permissionResolveType = 'permission.resolve';

/// Shape shared by every frame, in both directions. See docs/architecture/shared/05-websocket-protocol.md.
class Envelope {
  const Envelope({
    required this.v,
    required this.id,
    required this.kind,
    required this.type,
    required this.ts,
    this.traceId,
    this.correlationId,
    this.sessionId,
    this.seq,
    this.payload,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory Envelope.fromJson(Map<String, Object?> json) => Envelope(
        v: json['v']! as int,
        id: json['id']! as String,
        kind: json['kind']! as String,
        type: json['type']! as String,
        ts: json['ts']! as String,
        traceId: json['traceId'] as String?,
        correlationId: json['correlationId'] as String?,
        sessionId: json['sessionId'] as String?,
        seq: json['seq'] as int?,
        payload: json['payload'] as Map<String, Object?>?,
      );

  /// Protocol version. Adding an optional field or a new event does not change it; removing a field, renaming a type or changing a meaning does.
  final int v;

  /// ULID unique to this frame.
  final String id;

  /// What the frame is. `request` travels server to client and demands an answer — that is the case the whole protocol is designed around.
  final String kind;

  /// What the frame is, within its kind.
  final String type;

  /// ISO 8601 instant, in UTC.
  final String ts;

  /// Correlates this frame with the server logs of the same operation.
  final String? traceId;

  /// `id` of the frame that caused this one.
  final String? correlationId;

  /// Session the frame belongs to, when it belongs to one. It is what fan-out routes on, and what ties the many traces of a conversation together.
  final String? sessionId;

  /// Monotonic per stream, on events only — a stream is a session, or a subscription such as a watch of a folder. On a session it is what makes replay after a reconnect possible; a subscription has no replay, and a reconnect subscribes again from 1.
  final int? seq;

  /// Contents, defined per `type`.
  final Map<String, Object?>? payload;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'v': v,
      'id': id,
      'kind': kind,
      'type': type,
      'ts': ts,
    };

    if (traceId != null) {
      json['traceId'] = traceId;
    }

    if (correlationId != null) {
      json['correlationId'] = correlationId;
    }

    if (sessionId != null) {
      json['sessionId'] = sessionId;
    }

    if (seq != null) {
      json['seq'] = seq;
    }

    if (payload != null) {
      json['payload'] = payload;
    }

    return json;
  }
}

/// Whether [json] satisfies the conditional requirements of [Envelope].
///
/// `seq` is also required when `kind`
/// is `event` — replay is built on `seq`, and an event without one is a hole nobody can detect afterwards, so the schema is what charges it rather than the goodwill of whoever emits.
bool envelopeConditionalsHold(Map<String, Object?> json) {
  if (json['kind'] == 'event' && json['seq'] is! int) {
    return false;
  }

  return true;
}

/// A command was accepted — not that it finished. The outcome arrives as an event; waiting on this ack for a result reintroduces request/response where the protocol chose a stream.
class CommandAcceptedPayload {
  const CommandAcceptedPayload({
    required this.command,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory CommandAcceptedPayload.fromJson(Map<String, Object?> json) => CommandAcceptedPayload(
        command: json['command']! as String,
      );

  /// `type` of the command being acknowledged.
  final String command;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'command': command,
    };

    return json;
  }
}

/// What this server will accept, so the client does not have to discover it by being refused.
class ConnectionReadyPayloadLimits {
  const ConnectionReadyPayloadLimits({
    required this.maxFrameBytes,
    required this.maxFramesPerSecond,
    required this.maxAttachedSessions,
    required this.replayBufferSize,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ConnectionReadyPayloadLimits.fromJson(Map<String, Object?> json) => ConnectionReadyPayloadLimits(
        maxFrameBytes: json['maxFrameBytes']! as int,
        maxFramesPerSecond: json['maxFramesPerSecond']! as int,
        maxAttachedSessions: json['maxAttachedSessions']! as int,
        replayBufferSize: json['replayBufferSize']! as int,
      );

  /// Largest frame accepted, in bytes. Over it: `error` PAYLOAD_TOO_LARGE, and the socket stays.
  final int maxFrameBytes;

  /// Frames a client may send per second. Over it: `error` RATE_LIMITED with `params.retryAfterSeconds`; sending again inside that window closes with 4429.
  final int maxFramesPerSecond;

  /// Sessions one connection may watch at once. `session.attach` or `session.start` beyond it: `error` RATE_LIMITED.
  final int maxAttachedSessions;

  final int replayBufferSize;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'maxFrameBytes': maxFrameBytes,
      'maxFramesPerSecond': maxFramesPerSecond,
      'maxAttachedSessions': maxAttachedSessions,
      'replayBufferSize': replayBufferSize,
    };

    return json;
  }
}

/// Answer to a successful handshake. An ack, not an event: it acknowledges the command that caused it.
class ConnectionReadyPayload {
  const ConnectionReadyPayload({
    required this.connectionId,
    required this.serverVersion,
    required this.limits,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ConnectionReadyPayload.fromJson(Map<String, Object?> json) => ConnectionReadyPayload(
        connectionId: json['connectionId']! as String,
        serverVersion: json['serverVersion']! as String,
        limits: ConnectionReadyPayloadLimits.fromJson(json['limits']! as Map<String, Object?>),
      );

  final String connectionId;

  final String serverVersion;

  /// What this server will accept, so the client does not have to discover it by being refused.
  final ConnectionReadyPayloadLimits limits;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'connectionId': connectionId,
      'serverVersion': serverVersion,
      'limits': limits.toJson(),
    };

    return json;
  }
}

/// Answer to `session.attach` — and to a `session.start` whose `resumeSessionId` names a conversation already live for the caller. Says what was replayed and whether anything was lost.
class SessionAttachedPayload {
  const SessionAttachedPayload({
    required this.sessionId,
    required this.replayed,
    required this.oldestAvailableSeq,
    required this.gap,
    this.claudeSessionId,
    this.resumedFrom,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionAttachedPayload.fromJson(Map<String, Object?> json) => SessionAttachedPayload(
        sessionId: json['sessionId']! as String,
        replayed: json['replayed']! as int,
        oldestAvailableSeq: json['oldestAvailableSeq']! as int,
        gap: json['gap']! as bool,
        claudeSessionId: json['claudeSessionId'] as String?,
        resumedFrom: json['resumedFrom'] as String?,
      );

  final String sessionId;

  /// How many buffered events follow this ack.
  final int replayed;

  /// Lowest `seq` still in the buffer; 0 when the buffer is empty.
  final int oldestAvailableSeq;

  /// The requested sequence had already fallen out of the buffer. The client drops its local state and reloads over HTTP — it never stitches a partial hole.
  final bool gap;

  /// The conversation of a live session of Claude — where a client reloads from after a `gap`, which is exactly when the buffer no longer holds the `session.started` that named it. Absent for a stream that is not a conversation, such as the diagnostic round trip.
  final String? claudeSessionId;

  /// The conversation this session continues, when it is a resume. Present on the ack a `session.start` answers with when the conversation it asked to resume was already live for the caller: resuming what is live is an attach, never a second subprocess.
  final String? resumedFrom;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'replayed': replayed,
      'oldestAvailableSeq': oldestAvailableSeq,
      'gap': gap,
    };

    if (claudeSessionId != null) {
      json['claudeSessionId'] = claudeSessionId;
    }

    if (resumedFrom != null) {
      json['resumedFrom'] = resumedFrom;
    }

    return json;
  }
}

/// Answer to `workspace.watch`: the subscription exists, and the changes of the folder will arrive as `workspace.filesChanged` with this `watchId`.
class WorkspaceWatchingPayload {
  const WorkspaceWatchingPayload({
    required this.watchId,
    required this.workspacePath,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory WorkspaceWatchingPayload.fromJson(Map<String, Object?> json) => WorkspaceWatchingPayload(
        watchId: json['watchId']! as String,
        workspacePath: json['workspacePath']! as String,
      );

  /// The subscription. Its events carry it, and `seq` is monotonic per `watchId`, from 1.
  final String watchId;

  /// The real path of the folder being followed.
  final String workspacePath;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'watchId': watchId,
      'workspacePath': workspacePath,
    };

    return json;
  }
}

/// Who is connecting, for diagnostics and for the deprecation window.
class ConnectionAuthenticatePayloadClient {
  const ConnectionAuthenticatePayloadClient({
    required this.kind,
    required this.version,
    this.installId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ConnectionAuthenticatePayloadClient.fromJson(Map<String, Object?> json) => ConnectionAuthenticatePayloadClient(
        kind: json['kind']! as String,
        version: json['version']! as String,
        installId: json['installId'] as String?,
      );

  final String kind;

  final String version;

  /// The registered installation this socket belongs to, when the client is a device. Absent from a browser, which is not a device and never approves one. It is what lets revoking a device close its sockets at once, with 4401 — without it, a revoked phone would keep answering permission requests until its token expired.
  final String? installId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'kind': kind,
      'version': version,
    };

    if (installId != null) {
      json['installId'] = installId;
    }

    return json;
  }
}

/// Opens the connection. Without it inside 5 seconds the server closes with 4401.
class ConnectionAuthenticatePayload {
  const ConnectionAuthenticatePayload({
    required this.token,
    required this.locale,
    required this.client,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ConnectionAuthenticatePayload.fromJson(Map<String, Object?> json) => ConnectionAuthenticatePayload(
        token: json['token']! as String,
        locale: json['locale']! as String,
        client: ConnectionAuthenticatePayloadClient.fromJson(json['client']! as Map<String, Object?>),
      );

  /// OIDC access token. In the frame body, never in the query string — a query string leaks into proxy logs.
  final String token;

  /// Language of this connection, not of the user.
  final String locale;

  /// Who is connecting, for diagnostics and for the deprecation window.
  final ConnectionAuthenticatePayloadClient client;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'token': token,
      'locale': locale,
      'client': client.toJson(),
    };

    return json;
  }
}

/// Renews the credential without reopening the socket. An access token expiring on an open connection does not drop it; failing to renew within the 60 s grace period closes it with 4401.
class ConnectionReauthenticatePayload {
  const ConnectionReauthenticatePayload({
    required this.token,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ConnectionReauthenticatePayload.fromJson(Map<String, Object?> json) => ConnectionReauthenticatePayload(
        token: json['token']! as String,
      );

  /// The renewed OIDC access token.
  final String token;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'token': token,
    };

    return json;
  }
}

/// What the app says about itself on `POST /devices`. It travels over HTTP rather than the socket — a device has to exist before it may decide anything, and the handshake already needs to know which device it is — but the payload is one contract in three languages all the same.
class DeviceRegisterPayload {
  const DeviceRegisterPayload({
    required this.installId,
    required this.name,
    required this.platform,
    required this.appVersion,
    this.pushToken,
    this.locale,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory DeviceRegisterPayload.fromJson(Map<String, Object?> json) => DeviceRegisterPayload(
        installId: json['installId']! as String,
        name: json['name']! as String,
        platform: json['platform']! as String,
        appVersion: json['appVersion']! as String,
        pushToken: json['pushToken'] as String?,
        locale: json['locale'] as String?,
      );

  /// Identity of the installation, minted by the app on first run and kept in the operating system's secure storage. Never an identifier of the device itself: that one survives an uninstall, which is a privacy problem, and this one does not (D-01).
  final String installId;

  /// What the person will recognise in the approval list.
  final String name;

  /// Which operating system. Only Android is exercised in this plan (D-12); the app still builds for iOS.
  final String platform;

  /// Version of the app, for diagnostics and for the deprecation window.
  final String appVersion;

  /// The provider's token for this installation, when there is one. Absent is normal and not an error: a device with no token still watches sessions, and the app re-sends the token on every renewal (D-13).
  final String? pushToken;

  /// Language the push goes out in — the one exception to the rule that the backend never translates. Absent falls back to `en`.
  final String? locale;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'installId': installId,
      'name': name,
      'platform': platform,
      'appVersion': appVersion,
    };

    if (pushToken != null) {
      json['pushToken'] = pushToken;
    }

    if (locale != null) {
      json['locale'] = locale;
    }

    return json;
  }
}

/// Diagnostics of the gateway: it crosses every layer without touching the Agent SDK, and is the only smoke test that needs no Claude subprocess. It lives outside the session namespace on purpose — `diag` says it is diagnostics, which is what keeps the slice from becoming a public API with no owner. Omitting `sessionId` opens a session; sending one pings that session.
class DiagPingPayload {
  const DiagPingPayload({
    this.sessionId,
    required this.nonce,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory DiagPingPayload.fromJson(Map<String, Object?> json) => DiagPingPayload(
        sessionId: json['sessionId'] as String?,
        nonce: json['nonce']! as String,
      );

  /// Session to ping. Absent opens a new one, and the pong carries the id it got.
  final String? sessionId;

  /// Echoed back in the pong, so a client can tell its own round trip from someone else's on the same session.
  final String nonce;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'nonce': nonce,
    };

    if (sessionId != null) {
      json['sessionId'] = sessionId;
    }

    return json;
  }
}

/// Extends the deadline of a pending permission request. The payload carries **only** the request: the increment and the ceiling come from the backend configuration, because our timeout is the only protection against a hung session and the client does not get to choose that number. Idempotent by `requestId` — web and phone may both extend the same request.
class PermissionExtendPayload {
  const PermissionExtendPayload({
    required this.requestId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory PermissionExtendPayload.fromJson(Map<String, Object?> json) => PermissionExtendPayload(
        requestId: json['requestId']! as String,
      );

  /// The pending request to extend.
  final String requestId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'requestId': requestId,
    };

    return json;
  }
}

/// Starts observing a session. On a reconnect it also asks for the events missed while the socket was down.
class SessionAttachPayload {
  const SessionAttachPayload({
    required this.sessionId,
    this.resumeFromSeq,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionAttachPayload.fromJson(Map<String, Object?> json) => SessionAttachPayload(
        sessionId: json['sessionId']! as String,
        resumeFromSeq: json['resumeFromSeq'] as int?,
      );

  /// Session to observe.
  final String sessionId;

  /// Highest `seq` the client already has — `0` when it has none, which replays everything the buffer holds. The server replays from the next one, or answers `gap: true` when that sequence has fallen out of the buffer. Absent, nothing past is replayed: the connection only observes from now on.
  final int? resumeFromSeq;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
    };

    if (resumeFromSeq != null) {
      json['resumeFromSeq'] = resumeFromSeq;
    }

    return json;
  }
}

/// Takes a prompt out of the session's queue before it starts. Any watcher may, as any may send one. The outcome is `prompt.dequeued` with `reason: cancelled`, for everybody watching. A prompt that already started is `CONFLICT` (`session.error.queuedPromptStarted`); one the queue never had is `QUEUED_PROMPT_NOT_FOUND`.
class SessionCancelQueuedPromptPayload {
  const SessionCancelQueuedPromptPayload({
    required this.sessionId,
    required this.queueId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionCancelQueuedPromptPayload.fromJson(Map<String, Object?> json) => SessionCancelQueuedPromptPayload(
        sessionId: json['sessionId']! as String,
        queueId: json['queueId']! as String,
      );

  final String sessionId;

  /// What `prompt.queued` named the prompt.
  final String queueId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'queueId': queueId,
    };

    return json;
  }
}

/// Ends the session and releases its subprocess. Unlike every other command of the session, only the owner may send it.
class SessionClosePayload {
  const SessionClosePayload({
    required this.sessionId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionClosePayload.fromJson(Map<String, Object?> json) => SessionClosePayload(
        sessionId: json['sessionId']! as String,
      );

  final String sessionId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
    };

    return json;
  }
}

/// Stops observing a session. The counterpart of `session.attach`: without it, a client that moved on keeps receiving a stream it no longer shows.
class SessionDetachPayload {
  const SessionDetachPayload({
    required this.sessionId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionDetachPayload.fromJson(Map<String, Object?> json) => SessionDetachPayload(
        sessionId: json['sessionId']! as String,
      );

  /// Session to stop observing.
  final String sessionId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
    };

    return json;
  }
}

/// Interrupts the running turn — `query.interrupt()`. Any connection watching the session may send it.
class SessionInterruptPayload {
  const SessionInterruptPayload({
    required this.sessionId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionInterruptPayload.fromJson(Map<String, Object?> json) => SessionInterruptPayload(
        sessionId: json['sessionId']! as String,
      );

  final String sessionId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
    };

    return json;
  }
}

/// The lines of a `file` the prompt is about, inclusive and counted from 1. `endLine` before `startLine` is refused by the backend — an order between two fields is not a bound of one.
class SessionPromptPayloadAttachmentsItemRange {
  const SessionPromptPayloadAttachmentsItemRange({
    required this.startLine,
    required this.endLine,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionPromptPayloadAttachmentsItemRange.fromJson(Map<String, Object?> json) => SessionPromptPayloadAttachmentsItemRange(
        startLine: json['startLine']! as int,
        endLine: json['endLine']! as int,
      );

  final int startLine;

  final int endLine;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'startLine': startLine,
      'endLine': endLine,
    };

    return json;
  }
}

/// Whether [json] keeps within the bounds the schema gives [SessionPromptPayloadAttachmentsItemRange].
bool sessionPromptPayloadAttachmentsItemRangeLimitsHold(Map<String, Object?> json) {
  if (json['startLine'] is int && (json['startLine']! as int) < 1) {
    return false;
  }

  if (json['endLine'] is int && (json['endLine']! as int) < 1) {
    return false;
  }

  return true;
}

class SessionPromptPayloadAttachmentsItem {
  const SessionPromptPayloadAttachmentsItem({
    this.kind,
    this.path,
    this.mediaType,
    this.range,
    this.attachmentId,
    this.source,
    this.label,
    this.content,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionPromptPayloadAttachmentsItem.fromJson(Map<String, Object?> json) => SessionPromptPayloadAttachmentsItem(
        kind: json['kind'] as String?,
        path: json['path'] as String?,
        mediaType: json['mediaType'] as String?,
        range: json['range'] == null ? null : SessionPromptPayloadAttachmentsItemRange.fromJson(json['range']! as Map<String, Object?>),
        attachmentId: json['attachmentId'] as String?,
        source: json['source'] as String?,
        label: json['label'] as String?,
        content: json['content'] as String?,
      );

  /// What the attachment is. Absent reads as `file`, which is what keeps the field that existed before compatible — and `v` where it is.
  final String? kind;

  /// Path inside the session's folder, relative or absolute, for a `file` or a `folder`.
  final String? path;

  /// The type of the file, when the client knows it. Informative: the backend decides nothing by it.
  final String? mediaType;

  /// The lines of a `file` the prompt is about, inclusive and counted from 1. `endLine` before `startLine` is refused by the backend — an order between two fields is not a bound of one.
  final SessionPromptPayloadAttachmentsItemRange? range;

  /// What `POST /sessions/:sessionId/attachments` answered, for an `upload`: an image, or a text file dropped from the desktop. Unknown, expired or of another session is `ATTACHMENT_NOT_FOUND`.
  final String? attachmentId;

  /// The provider that holds the `text` — the integrated terminal of plan 10, when it exists. An enum read as a string, so a provider added later does not break a client already published.
  final String? source;

  /// How the `text` is introduced to Claude and shown on the chip: "terminal: bash".
  final String? label;

  /// The text itself, for a `text`. Bounded so that even at four bytes a character it fits the 64 KB frame beside the rest of the prompt.
  final String? content;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
    };

    if (kind != null) {
      json['kind'] = kind;
    }

    if (path != null) {
      json['path'] = path;
    }

    if (mediaType != null) {
      json['mediaType'] = mediaType;
    }

    if (range != null) {
      json['range'] = range?.toJson();
    }

    if (attachmentId != null) {
      json['attachmentId'] = attachmentId;
    }

    if (source != null) {
      json['source'] = source;
    }

    if (label != null) {
      json['label'] = label;
    }

    if (content != null) {
      json['content'] = content;
    }

    return json;
  }
}

/// Whether [json] satisfies the conditional requirements of [SessionPromptPayloadAttachmentsItem].
///
/// `path` is also required when `kind`
/// is absent — an attachment without a kind is the file attachment that existed before kinds did, and a file is named by its path.
/// `path` is also required when `kind`
/// is `file` — a file is named by its path inside the session's folder.
/// `path` is also required when `kind`
/// is `folder` — a folder is named by its path inside the session's folder.
/// `attachmentId` is also required when `kind`
/// is `upload` — an uploaded attachment travels over HTTP, and the prompt carries only the id the upload answered.
/// `source` is also required when `kind`
/// is `text` — text a provider holds goes to Claude labelled with where it came from, never as if the user had typed it.
/// `label` is also required when `kind`
/// is `text` — the label is what the delimited block is introduced by, and what the chip showed.
/// `content` is also required when `kind`
/// is `text` — text that is not on disk has nothing to be read from, so it travels itself.
bool sessionPromptPayloadAttachmentsItemConditionalsHold(Map<String, Object?> json) {
  if (json['kind'] == null && json['path'] is! String) {
    return false;
  }

  if (json['kind'] == 'file' && json['path'] is! String) {
    return false;
  }

  if (json['kind'] == 'folder' && json['path'] is! String) {
    return false;
  }

  if (json['kind'] == 'upload' && json['attachmentId'] is! String) {
    return false;
  }

  if (json['kind'] == 'text' && json['source'] is! String) {
    return false;
  }

  if (json['kind'] == 'text' && json['label'] is! String) {
    return false;
  }

  if (json['kind'] == 'text' && json['content'] is! String) {
    return false;
  }

  return true;
}

/// Whether [json] keeps within the bounds the schema gives [SessionPromptPayloadAttachmentsItem].
bool sessionPromptPayloadAttachmentsItemLimitsHold(Map<String, Object?> json) {
  if (json['label'] is String && (json['label']! as String).length > 200) {
    return false;
  }

  if (json['content'] is String && (json['content']! as String).length > 16384) {
    return false;
  }

  return true;
}

/// Sends one turn. A prompt that arrives while a turn is running is **queued** by the backend and runs next, on its own, the way the Claude Code UI does it — it is never refused, and every watcher sees it waiting (`prompt.queued`) until it starts or is taken out (`prompt.dequeued`).
class SessionPromptPayload {
  const SessionPromptPayload({
    required this.sessionId,
    required this.text,
    this.attachments,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionPromptPayload.fromJson(Map<String, Object?> json) => SessionPromptPayload(
        sessionId: json['sessionId']! as String,
        text: json['text']! as String,
        attachments: json['attachments'] == null ? null : (json['attachments']! as List<Object?>).map((item) => SessionPromptPayloadAttachmentsItem.fromJson(item! as Map<String, Object?>)).toList(growable: false),
      );

  final String sessionId;

  /// What the user typed.
  final String text;

  /// The context of the prompt, chosen with `@`, a drag or the editor: files, folders, ranges of lines, an uploaded attachment, or text a provider of the client holds (the terminal). A file or a folder is a **reference** — the backend checks it inside the session's folder, all or nothing, and Claude reads it through `Read`, which the trail records; its content never travels here (plan 08, D-01).
  final List<SessionPromptPayloadAttachmentsItem>? attachments;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'text': text,
    };

    if (attachments != null) {
      json['attachments'] = attachments?.map((item) => item.toJson()).toList(growable: false);
    }

    return json;
  }
}

/// Whether [json] keeps within the bounds the schema gives [SessionPromptPayload].
bool sessionPromptPayloadLimitsHold(Map<String, Object?> json) {
  if (json['attachments'] is List<Object?> && (json['attachments']! as List<Object?>).length > 20) {
    return false;
  }

  return true;
}

/// Puts one hunk of what a session changed in a file back the way it was before the session. Only while the disk still has what the session left — otherwise the file is `modifiedOutside` and is rejected whole, preserving it, by `session.rewindFiles` with `paths`. The outcome arrives as `session.rewound`, with `hunkId`. A `revision` that is no longer the disk's is `SESSION_CHANGE_STALE`; the same locks as an undo apply (`SESSION_LOCKED`).
class SessionRejectChangePayload {
  const SessionRejectChangePayload({
    required this.sessionId,
    required this.path,
    required this.hunkId,
    required this.revision,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionRejectChangePayload.fromJson(Map<String, Object?> json) => SessionRejectChangePayload(
        sessionId: json['sessionId']! as String,
        path: json['path']! as String,
        hunkId: json['hunkId']! as String,
        revision: json['revision']! as String,
      );

  final String sessionId;

  /// The file, as `GET /sessions/:sessionId/changes` named it.
  final String path;

  /// The hunk, as `GET /sessions/:sessionId/changes/file` named it.
  final String hunkId;

  /// The `revision` the hunks were computed against — the hash of the disk then. It is what keeps a hunk from being applied to a file that moved under it.
  final String revision;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'path': path,
      'hunkId': hunkId,
      'revision': revision,
    };

    return json;
  }
}

/// Puts the files a session wrote back the way they were **before** a turn began. The mechanism is ours, not `rewindFiles()` of the SDK: that one overwrites a manual edit in silence and takes no file filter, so a file somebody changed after the session is **preserved** here. Refused with `SESSION_LOCKED` while a turn is running, with `SESSION_NOT_FOUND` once the session is over, and with `INVALID_INPUT` for a point that is not a checkpoint of this session. The outcome arrives as `session.rewound`.
class SessionRewindFilesPayload {
  const SessionRewindFilesPayload({
    required this.sessionId,
    required this.promptId,
    this.paths,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionRewindFilesPayload.fromJson(Map<String, Object?> json) => SessionRewindFilesPayload(
        sessionId: json['sessionId']! as String,
        promptId: json['promptId']! as String,
        paths: json['paths'] == null ? null : (json['paths']! as List<Object?>).map((item) => item! as String).toList(growable: false),
      );

  final String sessionId;

  /// The turn to go back to, as `GET /sessions/:sessionId/checkpoints` names it — the `prompt_id` the hooks carry, never a message id of the transcript.
  final String promptId;

  /// Only these files, of everything the undo would touch — rejecting one file of what a session changed. Absent is every file. A path the undo does not reach is simply not touched; the outcome says what happened to each one it did.
  final List<String>? paths;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'promptId': promptId,
    };

    if (paths != null) {
      json['paths'] = paths;
    }

    return json;
  }
}

/// Changes the language of **this connection**, not of the user. A phone in Portuguese and a browser in English watch the same session at the same time.
class SessionSetLocalePayload {
  const SessionSetLocalePayload({
    required this.locale,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionSetLocalePayload.fromJson(Map<String, Object?> json) => SessionSetLocalePayload(
        locale: json['locale']! as String,
      );

  /// Language of this connection.
  final String locale;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'locale': locale,
    };

    return json;
  }
}

/// Changes the model of a running session.
class SessionSetModelPayload {
  const SessionSetModelPayload({
    required this.sessionId,
    required this.model,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionSetModelPayload.fromJson(Map<String, Object?> json) => SessionSetModelPayload(
        sessionId: json['sessionId']! as String,
        model: json['model']! as String,
      );

  final String sessionId;

  /// Model identifier, as the Agent SDK names it.
  final String model;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'model': model,
    };

    return json;
  }
}

/// Changes the permission mode of a running session.
class SessionSetPermissionModePayload {
  const SessionSetPermissionModePayload({
    required this.sessionId,
    required this.mode,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionSetPermissionModePayload.fromJson(Map<String, Object?> json) => SessionSetPermissionModePayload(
        sessionId: json['sessionId']! as String,
        mode: json['mode']! as String,
      );

  final String sessionId;

  /// The mode to switch to.
  final String mode;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'mode': mode,
    };

    return json;
  }
}

/// Opens a session on a workspace. The path is checked against the allowlist before anything else happens — it is the first line of defence, not a hint.
class SessionStartPayload {
  const SessionStartPayload({
    required this.workspacePath,
    this.model,
    this.permissionMode,
    this.effort,
    this.resumeSessionId,
    this.forkAt,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionStartPayload.fromJson(Map<String, Object?> json) => SessionStartPayload(
        workspacePath: json['workspacePath']! as String,
        model: json['model'] as String?,
        permissionMode: json['permissionMode'] as String?,
        effort: json['effort'] as String?,
        resumeSessionId: json['resumeSessionId'] as String?,
        forkAt: json['forkAt'] as String?,
      );

  /// Absolute path of the workspace. Outside the allowlist it is refused with WORKSPACE_NOT_ALLOWED, and a root that exists but belongs to someone else answers 404, never 403.
  final String workspacePath;

  /// Model to open with. Absent means the server default.
  final String? model;

  /// Permission mode to open with. Absent means the server default.
  final String? permissionMode;

  /// How much effort the model puts in, for the whole session. Absent is the installation's default. Chosen before the session exists, because changing it on a live one (`applyFlagSettings`) restarts the CLI's query and drops its hooks — measured in plan 08, D-16. A level the model does not take is `INVALID_INPUT` (`session.error.effortUnsupported`). An enum read as a string, so a level added later does not break a client.
  final String? effort;

  /// Session of the Agent SDK to resume instead of starting fresh.
  final String? resumeSessionId;

  /// Edit and resend: the `messageId` of the user prompt to rewrite. The conversation `resumeSessionId` names continues from **just before** it, always in a new id — the original stays as it was (plan 08, D-19). A point the conversation does not have is `INVALID_INPUT` (`session.error.forkPointUnknown`); one the CLI refuses is `SESSION_FORK_REJECTED`.
  final String? forkAt;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'workspacePath': workspacePath,
    };

    if (model != null) {
      json['model'] = model;
    }

    if (permissionMode != null) {
      json['permissionMode'] = permissionMode;
    }

    if (effort != null) {
      json['effort'] = effort;
    }

    if (resumeSessionId != null) {
      json['resumeSessionId'] = resumeSessionId;
    }

    if (forkAt != null) {
      json['forkAt'] = forkAt;
    }

    return json;
  }
}

/// Whether [json] satisfies the conditional requirements of [SessionStartPayload].
///
/// `resumeSessionId` is also required when `forkAt`
/// is present — a fork point is a message of a conversation, and only a resumed conversation has one.
bool sessionStartPayloadConditionalsHold(Map<String, Object?> json) {
  if (json['forkAt'] != null && json['resumeSessionId'] is! String) {
    return false;
  }

  return true;
}

/// Stops following a folder. Idempotent: a subscription that already ended — or never was this connection's — is acknowledged all the same, because a client that unwatches as it closes a tab races its own reconnection.
class WorkspaceUnwatchPayload {
  const WorkspaceUnwatchPayload({
    required this.watchId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory WorkspaceUnwatchPayload.fromJson(Map<String, Object?> json) => WorkspaceUnwatchPayload(
        watchId: json['watchId']! as String,
      );

  /// The subscription, as `workspace.watching` named it.
  final String watchId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'watchId': watchId,
    };

    return json;
  }
}

/// Starts following the changes on disk of an open folder, for the explorer and the editor. Answered with `workspace.watching`, which names the subscription; the changes then arrive as `workspace.filesChanged`, with a `seq` of their own that starts at 1. There is **no replay**: after a reconnect the client watches again — a new `watchId`, `seq` from 1 — and reloads the tree, because what matters after a drop is the disk as it is now. Refused with `INVALID_INPUT` (every invalid field in `details[]`), with the refusals of the folder (`WORKSPACE_NOT_ALLOWED`, `FORBIDDEN`, `WORKSPACE_NOT_FOUND`, `WORKSPACE_NOT_A_DIRECTORY`), with `WATCH_LIMIT_REACHED` past the ceiling of the connection and with `WATCH_UNAVAILABLE` when the system refuses another watch.
class WorkspaceWatchPayload {
  const WorkspaceWatchPayload({
    required this.workspacePath,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory WorkspaceWatchPayload.fromJson(Map<String, Object?> json) => WorkspaceWatchPayload(
        workspacePath: json['workspacePath']! as String,
      );

  /// The open folder, absolute — the same value `session.start` takes, and the `folder` of the HTTP routes of the files.
  final String workspacePath;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'workspacePath': workspacePath,
    };

    return json;
  }
}

/// Result of `diag.ping`, carrying the `seq` the hub assigned. Like every event it is fanned out to every connection observing the session, not only to the one that asked.
class DiagPongPayload {
  const DiagPongPayload({
    required this.sessionId,
    required this.pingedAt,
    required this.pingCount,
    required this.nonce,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory DiagPongPayload.fromJson(Map<String, Object?> json) => DiagPongPayload(
        sessionId: json['sessionId']! as String,
        pingedAt: json['pingedAt']! as String,
        pingCount: json['pingCount']! as int,
        nonce: json['nonce']! as String,
      );

  final String sessionId;

  /// ISO 8601 instant in UTC, read from the server clock.
  final String pingedAt;

  /// How many times this session has been pinged, counting this one.
  final int pingCount;

  /// Echo of the nonce the command carried.
  final String nonce;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'pingedAt': pingedAt,
      'pingCount': pingCount,
      'nonce': nonce,
    };

    return json;
  }
}

class ErrorPayloadDetailsItem {
  const ErrorPayloadDetailsItem({
    required this.field,
    required this.rule,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ErrorPayloadDetailsItem.fromJson(Map<String, Object?> json) => ErrorPayloadDetailsItem(
        field: json['field']! as String,
        rule: json['rule']! as String,
      );

  final String field;

  final String rule;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'field': field,
      'rule': rule,
    };

    return json;
  }
}

/// The error envelope, identical to the HTTP one. See docs/architecture/shared/04-errors-and-http.md.
class ErrorPayload {
  const ErrorPayload({
    required this.code,
    required this.messageKey,
    this.params,
    required this.traceId,
    this.httpEquivalent,
    this.details,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ErrorPayload.fromJson(Map<String, Object?> json) => ErrorPayload(
        code: json['code']! as String,
        messageKey: json['messageKey']! as String,
        params: json['params'] as Map<String, Object?>?,
        traceId: json['traceId']! as String,
        httpEquivalent: json['httpEquivalent'] as int?,
        details: json['details'] == null ? null : (json['details']! as List<Object?>).map((item) => ErrorPayloadDetailsItem.fromJson(item! as Map<String, Object?>)).toList(growable: false),
      );

  /// Stable, for client logic. Changing one is a breaking change.
  final String code;

  /// For display. The client translates it — the server never sends prose.
  final String messageKey;

  /// Interpolation values for the message key.
  final Map<String, Object?>? params;

  /// Lets a user report the problem and someone find it in the log.
  final String traceId;

  /// The status this error would carry over HTTP. A WebSocket frame has no status line, and the mapping in docs/architecture/shared/04-errors-and-http.md holds on both transports.
  final int? httpEquivalent;

  /// Validation only: every invalid field, not just the first.
  final List<ErrorPayloadDetailsItem>? details;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'code': code,
      'messageKey': messageKey,
      'traceId': traceId,
    };

    if (params != null) {
      json['params'] = params;
    }

    if (httpEquivalent != null) {
      json['httpEquivalent'] = httpEquivalent;
    }

    if (details != null) {
      json['details'] = details?.map((item) => item.toJson()).toList(growable: false);
    }

    return json;
  }
}

class MessageCompletedPayloadContentItem {
  const MessageCompletedPayloadContentItem({
    required this.type,
    this.text,
    this.thinking,
    this.toolUseId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory MessageCompletedPayloadContentItem.fromJson(Map<String, Object?> json) => MessageCompletedPayloadContentItem(
        type: json['type']! as String,
        text: json['text'] as String?,
        thinking: json['thinking'] as String?,
        toolUseId: json['toolUseId'] as String?,
      );

  /// Block kind — `text`, `thinking`, `redacted_thinking`, `tool_use`, `tool_result` and whatever the SDK adds next. Not an enum on purpose: a published app has to survive a kind added after it shipped.
  final String type;

  /// The text of a `text` block.
  final String? text;

  /// What the model thought, on a `thinking` block — in a field of its own and not in `text`, so a client that joins the `text` of every block never shows it as the answer. A `redacted_thinking` block has neither: it says the model thought, and nothing it thought.
  final String? thinking;

  final String? toolUseId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'type': type,
    };

    if (text != null) {
      json['text'] = text;
    }

    if (thinking != null) {
      json['thinking'] = thinking;
    }

    if (toolUseId != null) {
      json['toolUseId'] = toolUseId;
    }

    return json;
  }
}

/// A message is finished, with its content as blocks. It supersedes whatever the deltas of the same `messageId` accumulated — a client that missed a delta is made whole here.
class MessageCompletedPayload {
  const MessageCompletedPayload({
    required this.messageId,
    required this.role,
    this.promptedBy,
    required this.content,
    this.parentToolUseId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory MessageCompletedPayload.fromJson(Map<String, Object?> json) => MessageCompletedPayload(
        messageId: json['messageId']! as String,
        role: json['role']! as String,
        promptedBy: json['promptedBy'] as String?,
        content: (json['content']! as List<Object?>).map((item) => MessageCompletedPayloadContentItem.fromJson(item! as Map<String, Object?>)).toList(growable: false),
        parentToolUseId: json['parentToolUseId'] as String?,
      );

  final String messageId;

  final String role;

  /// Who sent it, on a `user` message. It is what lets the UI say "you sent this from your phone" instead of showing an authorless turn.
  final String? promptedBy;

  /// The blocks of the message, in order.
  final List<MessageCompletedPayloadContentItem> content;

  /// Set when this comes from a subagent: the `toolUseId` of the `Task` that opened it. Absent on the main conversation.
  final String? parentToolUseId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'messageId': messageId,
      'role': role,
      'content': content.map((item) => item.toJson()).toList(growable: false),
    };

    if (promptedBy != null) {
      json['promptedBy'] = promptedBy;
    }

    if (parentToolUseId != null) {
      json['parentToolUseId'] = parentToolUseId;
    }

    return json;
  }
}

/// A fragment of the assistant's answer, from the SDK's `stream_event`. The client accumulates by `messageId`; it never concatenates blindly in arrival order.
class MessageDeltaPayload {
  const MessageDeltaPayload({
    required this.messageId,
    required this.delta,
    this.blockType,
    this.parentToolUseId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory MessageDeltaPayload.fromJson(Map<String, Object?> json) => MessageDeltaPayload(
        messageId: json['messageId']! as String,
        delta: json['delta']! as String,
        blockType: json['blockType'] as String?,
        parentToolUseId: json['parentToolUseId'] as String?,
      );

  /// What the fragments of one message are grouped by.
  final String messageId;

  /// The text of this fragment, and only of this one.
  final String delta;

  /// What the fragment is part of: the answer, or Claude's thinking before it. Absent reads as `text`. An enum read as a string, so a block kind added later is not a crash.
  final String? blockType;

  /// Set when the fragment comes from a subagent: the `toolUseId` of the `Task` that opened it. The client nests it there instead of in the conversation.
  final String? parentToolUseId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'messageId': messageId,
      'delta': delta,
    };

    if (blockType != null) {
      json['blockType'] = blockType;
    }

    if (parentToolUseId != null) {
      json['parentToolUseId'] = parentToolUseId;
    }

    return json;
  }
}

/// The deadline of a pending request moved. Fanned out to every connection, because the phone and the browser are looking at the same countdown.
class PermissionExtendedPayload {
  const PermissionExtendedPayload({
    required this.requestId,
    required this.expiresAt,
    required this.remainingExtensions,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory PermissionExtendedPayload.fromJson(Map<String, Object?> json) => PermissionExtendedPayload(
        requestId: json['requestId']! as String,
        expiresAt: json['expiresAt']! as String,
        remainingExtensions: json['remainingExtensions']! as int,
      );

  final String requestId;

  /// The new deadline, ISO 8601 in UTC.
  final String expiresAt;

  /// How many extensions are left before the configured ceiling. It is what stops the UI promising an extension that no longer exists.
  final int remainingExtensions;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'requestId': requestId,
      'expiresAt': expiresAt,
      'remainingExtensions': remainingExtensions,
    };

    return json;
  }
}

class PermissionRequestedPayloadSuggestionsItem {
  const PermissionRequestedPayloadSuggestionsItem({
    required this.scope,
    required this.labelKey,
    this.pattern,
    this.lifetimeMs,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory PermissionRequestedPayloadSuggestionsItem.fromJson(Map<String, Object?> json) => PermissionRequestedPayloadSuggestionsItem(
        scope: json['scope']! as String,
        labelKey: json['labelKey']! as String,
        pattern: json['pattern'] as String?,
        lifetimeMs: json['lifetimeMs'] as int?,
      );

  final String scope;

  /// An i18n key. The server never sends prose.
  final String labelKey;

  /// What a rule granted by this suggestion would match, in the grammar of the Claude Code settings — the narrowest pattern that covers this invocation. Present on `project` and `always`; a client never offers one of those without it.
  final String? pattern;

  /// How long a rule granted by this suggestion would live, counted from the answer. Present on `project` and `always`; the number is the installation's, never the client's.
  final int? lifetimeMs;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'scope': scope,
      'labelKey': labelKey,
    };

    if (pattern != null) {
      json['pattern'] = pattern;
    }

    if (lifetimeMs != null) {
      json['lifetimeMs'] = lifetimeMs;
    }

    return json;
  }
}

/// The one `request` that travels server to client, and the reason the whole protocol is a socket instead of a stream: `canUseTool` has blocked the agent loop and it stays blocked until somebody answers or the deadline passes. Answered with the `permission.resolve` response.
class PermissionRequestedPayload {
  const PermissionRequestedPayload({
    required this.requestId,
    required this.toolUseId,
    required this.toolName,
    required this.title,
    this.description,
    required this.input,
    required this.riskHint,
    required this.defaultToNo,
    required this.expiresAt,
    this.suggestions,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory PermissionRequestedPayload.fromJson(Map<String, Object?> json) => PermissionRequestedPayload(
        requestId: json['requestId']! as String,
        toolUseId: json['toolUseId']! as String,
        toolName: json['toolName']! as String,
        title: json['title']! as String,
        description: json['description'] as String?,
        input: json['input']! as Map<String, Object?>,
        riskHint: json['riskHint']! as String,
        defaultToNo: json['defaultToNo']! as bool,
        expiresAt: json['expiresAt']! as String,
        suggestions: json['suggestions'] == null ? null : (json['suggestions']! as List<Object?>).map((item) => PermissionRequestedPayloadSuggestionsItem.fromJson(item! as Map<String, Object?>)).toList(growable: false),
      );

  /// Idempotency is by **this** field, never by `toolUseId`.
  final String requestId;

  /// The invocation this request is about, tying it to the `tool.started` already on screen.
  final String toolUseId;

  final String toolName;

  /// Short label of what is being asked, derived by the backend.
  final String title;

  /// The detail a human needs to decide — the command line, the path being written.
  final String? description;

  /// The exact input the tool would run with. What is shown is what executes.
  final Map<String, Object?> input;

  /// Derived in the backend, by a per-tool list **plus** a heuristic over the input, and it fails closed: a command the heuristic does not recognise is marked `destructive`. A false positive is an annoyance; a false negative is the accident.
  final String riskHint;

  /// The UI pre-selects refusal. Silence never authorises.
  final bool defaultToNo;

  /// When the request is denied automatically, ISO 8601 in UTC. Ours is the only timeout there is — the CLI imposes none.
  final String expiresAt;

  /// Scopes the UI may offer beyond a one-off yes.
  final List<PermissionRequestedPayloadSuggestionsItem>? suggestions;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'requestId': requestId,
      'toolUseId': toolUseId,
      'toolName': toolName,
      'title': title,
      'input': input,
      'riskHint': riskHint,
      'defaultToNo': defaultToNo,
      'expiresAt': expiresAt,
    };

    if (description != null) {
      json['description'] = description;
    }

    if (suggestions != null) {
      json['suggestions'] = suggestions?.map((item) => item.toJson()).toList(growable: false);
    }

    return json;
  }
}

/// A permission request is settled. It reaches **every** connection, including the one that answered — that is how a second client learns it lost the race, and who won it.
class PermissionResolvedPayload {
  const PermissionResolvedPayload({
    required this.requestId,
    required this.decision,
    required this.auto,
    this.resolvedBy,
    this.resolvedFrom,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory PermissionResolvedPayload.fromJson(Map<String, Object?> json) => PermissionResolvedPayload(
        requestId: json['requestId']! as String,
        decision: json['decision']! as String,
        auto: json['auto']! as bool,
        resolvedBy: json['resolvedBy'] as String?,
        resolvedFrom: json['resolvedFrom'] as String?,
      );

  /// The request that was settled. A client matches it against the card it is showing, never against `toolUseId`.
  final String requestId;

  /// What was decided. First answer wins, so this is the decision that reached `canUseTool`, not necessarily the one this client sent.
  final String decision;

  /// The server decided it, with nobody answering — the deadline passed, or a rule the user granted earlier (`session`, `project` or `always`) matched. A request a rule settles is never put to anybody, and this event is how every screen watching still learns that something ran in the user's name. Silence never authorises, so an automatic decision is always `deny` unless a rule allowed it.
  final bool auto;

  /// Who answered. Required whenever `auto` is false, so "approved on your phone 2 min ago" is something the UI can actually say.
  final String? resolvedBy;

  /// Which client answered.
  final String? resolvedFrom;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'requestId': requestId,
      'decision': decision,
      'auto': auto,
    };

    if (resolvedBy != null) {
      json['resolvedBy'] = resolvedBy;
    }

    if (resolvedFrom != null) {
      json['resolvedFrom'] = resolvedFrom;
    }

    return json;
  }
}

/// Whether [json] satisfies the conditional requirements of [PermissionResolvedPayload].
///
/// `resolvedBy` is also required when `auto`
/// is `false` — a decision a human made has an author; only the automatic deny has none.
bool permissionResolvedPayloadConditionalsHold(Map<String, Object?> json) {
  if (json['auto'] == false && json['resolvedBy'] is! String) {
    return false;
  }

  return true;
}

/// A prompt left the queue: it started, or somebody took it out. The positions of the ones behind it move up by one.
class PromptDequeuedPayload {
  const PromptDequeuedPayload({
    required this.queueId,
    required this.reason,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory PromptDequeuedPayload.fromJson(Map<String, Object?> json) => PromptDequeuedPayload(
        queueId: json['queueId']! as String,
        reason: json['reason']! as String,
      );

  final String queueId;

  /// `started` — the turn it asked for began; `cancelled` — somebody took it out before that.
  final String reason;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'queueId': queueId,
      'reason': reason,
    };

    return json;
  }
}

/// A prompt is waiting for the running turn to end. The queue is the backend's, not the SDK's — a prompt handed to the SDK cannot be taken back (plan 08, D-14) — so every watcher sees the same queue, and any of them can take one out with `session.cancelQueuedPrompt`.
class PromptQueuedPayload {
  const PromptQueuedPayload({
    required this.queueId,
    required this.position,
    required this.promptedBy,
    required this.preview,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory PromptQueuedPayload.fromJson(Map<String, Object?> json) => PromptQueuedPayload(
        queueId: json['queueId']! as String,
        position: json['position']! as int,
        promptedBy: json['promptedBy']! as String,
        preview: json['preview']! as String,
      );

  /// What `session.cancelQueuedPrompt` names it by.
  final String queueId;

  /// Its place in the queue, from 1.
  final int position;

  /// Who sent it.
  final String promptedBy;

  /// The start of what was typed, for the row of the queue. Cut by the backend; the whole prompt is the turn's, when it runs.
  final String preview;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'queueId': queueId,
      'position': position,
      'promptedBy': promptedBy,
      'preview': preview,
    };

    return json;
  }
}

/// The session ended and its subprocess is gone. The replay buffer **survives** this event — opening a closed session shows the terminal state plus whatever the ring still holds, labelled as partial.
class SessionClosedPayload {
  const SessionClosedPayload({
    required this.sessionId,
    required this.reason,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionClosedPayload.fromJson(Map<String, Object?> json) => SessionClosedPayload(
        sessionId: json['sessionId']! as String,
        reason: json['reason']! as String,
      );

  final String sessionId;

  /// Why it ended. `auditUnavailable` is the second consecutive audit write failure — a session that cannot be recorded does not keep running. `idleTimeout` is the installation reclaiming a session nobody used for longer than its TTL; the conversation is still in the history and can be resumed.
  final String reason;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'reason': reason,
    };

    return json;
  }
}

/// The conversation was compacted: what came before is now a summary Claude carries forward. Said on its own rather than as a status, because a client that keeps the turns on screen has to mark the point — and the context meter drops there.
class SessionCompactedPayload {
  const SessionCompactedPayload({
    required this.trigger,
    this.preTokens,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionCompactedPayload.fromJson(Map<String, Object?> json) => SessionCompactedPayload(
        trigger: json['trigger']! as String,
        preTokens: json['preTokens'] as int?,
      );

  /// `manual` — somebody sent `/compact`; `auto` — the context was full and Claude compacted it.
  final String trigger;

  /// How many tokens the context held before, when the SDK says.
  final int? preTokens;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'trigger': trigger,
    };

    if (preTokens != null) {
      json['preTokens'] = preTokens;
    }

    return json;
  }
}

class SessionRewoundPayloadRevertedItem {
  const SessionRewoundPayloadRevertedItem({
    required this.path,
    required this.action,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionRewoundPayloadRevertedItem.fromJson(Map<String, Object?> json) => SessionRewoundPayloadRevertedItem(
        path: json['path']! as String,
        action: json['action']! as String,
      );

  final String path;

  /// `deleted` for a file the session created: before the turn it was not there.
  final String action;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'path': path,
      'action': action,
    };

    return json;
  }
}

class SessionRewoundPayloadPreservedItem {
  const SessionRewoundPayloadPreservedItem({
    required this.path,
    required this.reason,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionRewoundPayloadPreservedItem.fromJson(Map<String, Object?> json) => SessionRewoundPayloadPreservedItem(
        path: json['path']! as String,
        reason: json['reason']! as String,
      );

  final String path;

  /// `modifiedOutside` — somebody changed it after the session did; `notRestorable` — it was too large or unreadable to snapshot; `unsafePath` — it became a link or something other than a regular file, or its directory no longer resolves; `noBaseline` — nothing records how the session left it, so the undo will not guess.
  final String reason;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'path': path,
      'reason': reason,
    };

    return json;
  }
}

class SessionRewoundPayloadUnchangedItem {
  const SessionRewoundPayloadUnchangedItem({
    required this.path,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionRewoundPayloadUnchangedItem.fromJson(Map<String, Object?> json) => SessionRewoundPayloadUnchangedItem(
        path: json['path']! as String,
      );

  final String path;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'path': path,
    };

    return json;
  }
}

class SessionRewoundPayloadFailedItem {
  const SessionRewoundPayloadFailedItem({
    required this.path,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionRewoundPayloadFailedItem.fromJson(Map<String, Object?> json) => SessionRewoundPayloadFailedItem(
        path: json['path']! as String,
      );

  final String path;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'path': path,
    };

    return json;
  }
}

/// What an undo did to the disk, file by file — never a boolean. Fanned out to every connection watching the session, because the files changed for all of them. A path in `failed` means the undo stopped short there; an `error` with `INTERNAL_ERROR` follows, and nothing listed as reverted is left half-written.
class SessionRewoundPayload {
  const SessionRewoundPayload({
    required this.promptId,
    required this.reverted,
    required this.preserved,
    required this.unchanged,
    required this.failed,
    this.hunkId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionRewoundPayload.fromJson(Map<String, Object?> json) => SessionRewoundPayload(
        promptId: json['promptId']! as String,
        reverted: (json['reverted']! as List<Object?>).map((item) => SessionRewoundPayloadRevertedItem.fromJson(item! as Map<String, Object?>)).toList(growable: false),
        preserved: (json['preserved']! as List<Object?>).map((item) => SessionRewoundPayloadPreservedItem.fromJson(item! as Map<String, Object?>)).toList(growable: false),
        unchanged: (json['unchanged']! as List<Object?>).map((item) => SessionRewoundPayloadUnchangedItem.fromJson(item! as Map<String, Object?>)).toList(growable: false),
        failed: (json['failed']! as List<Object?>).map((item) => SessionRewoundPayloadFailedItem.fromJson(item! as Map<String, Object?>)).toList(growable: false),
        hunkId: json['hunkId'] as String?,
      );

  /// The turn the files went back to.
  final String promptId;

  /// Paths put back the way they were before the turn.
  final List<SessionRewoundPayloadRevertedItem> reverted;

  /// Paths left as they are, each with the reason.
  final List<SessionRewoundPayloadPreservedItem> preserved;

  /// Paths that were already the way they were before the turn. A second undo to the same point lands here — it is idempotent.
  final List<SessionRewoundPayloadUnchangedItem> unchanged;

  /// Paths the undo tried to put back and could not. Each is left exactly as it was: restoring writes a temporary file beside it and renames it over.
  final List<SessionRewoundPayloadFailedItem> failed;

  /// Set when only one hunk went back (`session.rejectChange`): the file is the one path of `reverted`, and the rest of what the session changed in it stays.
  final String? hunkId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'promptId': promptId,
      'reverted': reverted.map((item) => item.toJson()).toList(growable: false),
      'preserved': preserved.map((item) => item.toJson()).toList(growable: false),
      'unchanged': unchanged.map((item) => item.toJson()).toList(growable: false),
      'failed': failed.map((item) => item.toJson()).toList(growable: false),
    };

    if (hunkId != null) {
      json['hunkId'] = hunkId;
    }

    return json;
  }
}

/// The session is open and the Agent SDK has initialised. Normalised from the SDK's `system:init` — an SDKMessage is never emitted raw (ADR-006).
class SessionStartedPayload {
  const SessionStartedPayload({
    required this.sessionId,
    required this.workspacePath,
    required this.model,
    required this.permissionMode,
    required this.claudeSessionId,
    this.resumedFrom,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionStartedPayload.fromJson(Map<String, Object?> json) => SessionStartedPayload(
        sessionId: json['sessionId']! as String,
        workspacePath: json['workspacePath']! as String,
        model: json['model']! as String,
        permissionMode: json['permissionMode']! as String,
        claudeSessionId: json['claudeSessionId']! as String,
        resumedFrom: json['resumedFrom'] as String?,
      );

  final String sessionId;

  /// The workspace the session runs in, already normalised and already inside the allowlist.
  final String workspacePath;

  final String model;

  final String permissionMode;

  /// The id of the conversation in Claude's store, which is not ours: it is what `GET /transcripts/:sessionId/messages` reads and what a later `session.start` takes as `resumeSessionId`. Equal to `resumedFrom` when one of our own conversations is continued in place; new when a conversation begun elsewhere is forked.
  final String claudeSessionId;

  /// The conversation this session continues, when it is a resume. Absent for a fresh session. The history before the first turn of this session is read from it, over HTTP — the replay buffer only ever holds what this session said.
  final String? resumedFrom;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'workspacePath': workspacePath,
      'model': model,
      'permissionMode': permissionMode,
      'claudeSessionId': claudeSessionId,
    };

    if (resumedFrom != null) {
      json['resumedFrom'] = resumedFrom;
    }

    return json;
  }
}

/// Where the session stands. Derived by us, not read off a single SDK message.
class SessionStatusChangedPayload {
  const SessionStatusChangedPayload({
    required this.status,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionStatusChangedPayload.fromJson(Map<String, Object?> json) => SessionStatusChangedPayload(
        status: json['status']! as String,
      );

  /// `waitingPermission` is the one that matters: the agent loop is blocked on a human.
  final String status;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'status': status,
    };

    return json;
  }
}

/// A tool invocation ended, from the `tool_result` the SDK reports on a `user` message.
class ToolCompletedPayload {
  const ToolCompletedPayload({
    required this.toolUseId,
    required this.status,
    this.summary,
    this.parentToolUseId,
    this.taskId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ToolCompletedPayload.fromJson(Map<String, Object?> json) => ToolCompletedPayload(
        toolUseId: json['toolUseId']! as String,
        status: json['status']! as String,
        summary: json['summary'] as String?,
        parentToolUseId: json['parentToolUseId'] as String?,
        taskId: json['taskId'] as String?,
      );

  final String toolUseId;

  /// `denied` is not a failure of the tool: it is a human having said no, and the UI reads the two differently.
  final String status;

  /// A short result for the timeline. The full output is the transcript's job, not this event's.
  final String? summary;

  /// Set when this comes from a subagent: the `toolUseId` of the `Task` that opened it. Absent on the main conversation.
  final String? parentToolUseId;

  /// The task of the list a `TaskCreate` made or a `TaskUpdate` changed — taken from the tool's structured result live, and from its result in the history. Absent for every other tool. The `summary` is the CLI's text, cut, and never carries it reliably (plan 08, B-20).
  final String? taskId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'toolUseId': toolUseId,
      'status': status,
    };

    if (summary != null) {
      json['summary'] = summary;
    }

    if (parentToolUseId != null) {
      json['parentToolUseId'] = parentToolUseId;
    }

    if (taskId != null) {
      json['taskId'] = taskId;
    }

    return json;
  }
}

/// Output of a tool while it is still running, from the SDK's `tool_progress`.
class ToolProgressPayload {
  const ToolProgressPayload({
    required this.toolUseId,
    required this.chunk,
    this.parentToolUseId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ToolProgressPayload.fromJson(Map<String, Object?> json) => ToolProgressPayload(
        toolUseId: json['toolUseId']! as String,
        chunk: json['chunk']! as String,
        parentToolUseId: json['parentToolUseId'] as String?,
      );

  final String toolUseId;

  /// This fragment of the output, and only this one.
  final String chunk;

  /// Set when this comes from a subagent: the `toolUseId` of the `Task` that opened it. Absent on the main conversation.
  final String? parentToolUseId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'toolUseId': toolUseId,
      'chunk': chunk,
    };

    if (parentToolUseId != null) {
      json['parentToolUseId'] = parentToolUseId;
    }

    return json;
  }
}

/// A tool invocation began. Emitted for **every** tool, including the ones no human was asked about — the audit trail is anchored on the same hook, for exactly that reason (ADR-011).
class ToolStartedPayload {
  const ToolStartedPayload({
    required this.toolUseId,
    required this.toolName,
    required this.input,
    this.title,
    this.parentToolUseId,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ToolStartedPayload.fromJson(Map<String, Object?> json) => ToolStartedPayload(
        toolUseId: json['toolUseId']! as String,
        toolName: json['toolName']! as String,
        input: json['input']! as Map<String, Object?>,
        title: json['title'] as String?,
        parentToolUseId: json['parentToolUseId'] as String?,
      );

  /// The SDK's id for this invocation. It is what ties started, progress and completed together.
  final String toolUseId;

  final String toolName;

  /// The exact input the tool was called with.
  final Map<String, Object?> input;

  /// A short human label for the invocation, already derived by the backend.
  final String? title;

  /// Set when this comes from a subagent: the `toolUseId` of the `Task` that opened it. Absent on the main conversation.
  final String? parentToolUseId;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'toolUseId': toolUseId,
      'toolName': toolName,
      'input': input,
    };

    if (title != null) {
      json['title'] = title;
    }

    if (parentToolUseId != null) {
      json['parentToolUseId'] = parentToolUseId;
    }

    return json;
  }
}

/// A turn finished, from the SDK's `result`. It is what closes the turn in the UI and what carries its cost.
class TurnCompletedPayload {
  const TurnCompletedPayload({
    required this.turnId,
    this.promptedBy,
    required this.usage,
    required this.costUsd,
    required this.durationMs,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory TurnCompletedPayload.fromJson(Map<String, Object?> json) => TurnCompletedPayload(
        turnId: json['turnId']! as String,
        promptedBy: json['promptedBy'] as String?,
        usage: json['usage']! as Map<String, Object?>,
        costUsd: json['costUsd']! as String,
        durationMs: json['durationMs']! as int,
      );

  final String turnId;

  /// Who sent the prompt this turn answered.
  final String? promptedBy;

  /// Token counts as the SDK reports them. An open map on purpose — the SDK adds fields to it, and a closed shape here would drop them.
  final Map<String, Object?> usage;

  /// Cost of the turn, as a decimal string. A string and not a number because money through a float is money that rounds where nobody looked.
  final String costUsd;

  final int durationMs;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'turnId': turnId,
      'usage': usage,
      'costUsd': costUsd,
      'durationMs': durationMs,
    };

    if (promptedBy != null) {
      json['promptedBy'] = promptedBy;
    }

    return json;
  }
}

class WorkspaceFilesChangedPayloadChangesItem {
  const WorkspaceFilesChangedPayloadChangesItem({
    required this.path,
    required this.kind,
    this.origin,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory WorkspaceFilesChangedPayloadChangesItem.fromJson(Map<String, Object?> json) => WorkspaceFilesChangedPayloadChangesItem(
        path: json['path']! as String,
        kind: json['kind']! as String,
        origin: json['origin'] as String?,
      );

  /// Relative to the folder, POSIX.
  final String path;

  final String kind;

  /// Who changed it, as far as the server can tell: a write of Claude's, a write of a person through the files routes, or anything else. A label, never a decision — absent when the server cannot say.
  final String? origin;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'path': path,
      'kind': kind,
    };

    if (origin != null) {
      json['origin'] = origin;
    }

    return json;
  }
}

/// What changed on disk in a folder being followed, coalesced. The frame's `seq` belongs to the subscription, not to any session: monotonic per `watchId`, from 1, and never replayed. A client that is not following this `watchId` — the mobile app never asks to — ignores it, and never lets its `seq` move the resume point of a session.
class WorkspaceFilesChangedPayload {
  const WorkspaceFilesChangedPayload({
    required this.watchId,
    required this.changes,
    this.overflow,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory WorkspaceFilesChangedPayload.fromJson(Map<String, Object?> json) => WorkspaceFilesChangedPayload(
        watchId: json['watchId']! as String,
        changes: (json['changes']! as List<Object?>).map((item) => WorkspaceFilesChangedPayloadChangesItem.fromJson(item! as Map<String, Object?>)).toList(growable: false),
        overflow: json['overflow'] as bool?,
      );

  final String watchId;

  /// Each path that changed, relative to the folder, with what happened to it.
  final List<WorkspaceFilesChangedPayloadChangesItem> changes;

  /// More changed than the event carries: the client reloads what it shows instead of patching it.
  final bool? overflow;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'watchId': watchId,
      'changes': changes.map((item) => item.toJson()).toList(growable: false),
    };

    if (overflow != null) {
      json['overflow'] = overflow;
    }

    return json;
  }
}

/// A subscription ended without the client asking: nothing more arrives for this `watchId`. The client says so where the folder is shown, and watches again only when the reason allows.
class WorkspaceWatchStoppedPayload {
  const WorkspaceWatchStoppedPayload({
    required this.watchId,
    required this.reason,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory WorkspaceWatchStoppedPayload.fromJson(Map<String, Object?> json) => WorkspaceWatchStoppedPayload(
        watchId: json['watchId']! as String,
        reason: json['reason']! as String,
      );

  final String watchId;

  /// `allowlistChanged` — the folder left the allowlist in a reload; `folderDeleted` — the folder is gone from the disk; `systemLimit` — the operating system stopped delivering changes.
  final String reason;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'watchId': watchId,
      'reason': reason,
    };

    return json;
  }
}

/// The answer to `permission.requested`, carrying its `id` in `correlationId`. Resolving the same `requestId` twice is a silent ack and **one** execution, never an error and never a double run — several clients watch one session, and a client may resend after reconnecting.
class PermissionResolvePayload {
  const PermissionResolvePayload({
    required this.requestId,
    required this.decision,
    this.scope,
    this.reason,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory PermissionResolvePayload.fromJson(Map<String, Object?> json) => PermissionResolvePayload(
        requestId: json['requestId']! as String,
        decision: json['decision']! as String,
        scope: json['scope'] as String?,
        reason: json['reason'] as String?,
      );

  /// The request being answered. Idempotency keys on it, so resending after a reconnect costs nothing.
  final String requestId;

  /// Yes or no. There is no third value: silence is handled by the deadline, and it denies.
  final String decision;

  /// How far the decision reaches. Absent means `once`. `session` leaves a rule that dies with the session; `project` and `always` persist a rule — the narrowest pattern covering this invocation, with the configured default lifetime — that answers future requests without asking and is revoked through `DELETE /permission-rules/:ruleId`. An invocation with nothing a pattern can name cannot be granted `project` or `always`: that is `INVALID_INPUT`, never a rule for the whole tool.
  final String? scope;

  /// Why it was refused. Required whenever `decision` is `deny` — the schema carries the condition, so no end has to remember it.
  final String? reason;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'requestId': requestId,
      'decision': decision,
    };

    if (scope != null) {
      json['scope'] = scope;
    }

    if (reason != null) {
      json['reason'] = reason;
    }

    return json;
  }
}

/// Whether [json] satisfies the conditional requirements of [PermissionResolvePayload].
///
/// `reason` is also required when `decision`
/// is `deny` — the reason goes into the audit trail and back to Claude as a message; a refusal nobody can account for is a refusal nobody can learn from.
bool permissionResolvePayloadConditionalsHold(Map<String, Object?> json) {
  if (json['decision'] == 'deny' && json['reason'] is! String) {
    return false;
  }

  return true;
}
