// Generated by `pnpm contracts:generate` from packages/contracts/schema/. Do not edit.
// `pnpm contracts:check` fails when this file and the schema disagree.

// dart format off

/// The protocol version this build speaks.
const int protocolVersion = 1;

/// Every frame `type` the classes below cover.
const List<String> frameTypes = <String>[
  'command.accepted',
  'connection.ready',
  'session.attached',
  'connection.authenticate',
  'connection.reauthenticate',
  'session.attach',
  'session.ping',
  'error',
  'session.pong',
];

/// `kind` of a command.accepted frame.
const String commandAcceptedKind = 'ack';

/// `type` of a command.accepted frame.
const String commandAcceptedType = 'command.accepted';

/// `kind` of a connection.ready frame.
const String connectionReadyKind = 'ack';

/// `type` of a connection.ready frame.
const String connectionReadyType = 'connection.ready';

/// `kind` of a session.attached frame.
const String sessionAttachedKind = 'ack';

/// `type` of a session.attached frame.
const String sessionAttachedType = 'session.attached';

/// `kind` of a connection.authenticate frame.
const String connectionAuthenticateKind = 'command';

/// `type` of a connection.authenticate frame.
const String connectionAuthenticateType = 'connection.authenticate';

/// `kind` of a connection.reauthenticate frame.
const String connectionReauthenticateKind = 'command';

/// `type` of a connection.reauthenticate frame.
const String connectionReauthenticateType = 'connection.reauthenticate';

/// `kind` of a session.attach frame.
const String sessionAttachKind = 'command';

/// `type` of a session.attach frame.
const String sessionAttachType = 'session.attach';

/// `kind` of a session.ping frame.
const String sessionPingKind = 'command';

/// `type` of a session.ping frame.
const String sessionPingType = 'session.ping';

/// `kind` of a error frame.
const String errorKind = 'error';

/// `type` of a error frame.
const String errorType = 'error';

/// `kind` of a session.pong frame.
const String sessionPongKind = 'event';

/// `type` of a session.pong frame.
const String sessionPongType = 'session.pong';

/// Shape shared by every frame, in both directions. See docs/architecture/shared/05-websocket-protocol.md.
class Envelope {
  const Envelope({
    required this.v,
    required this.id,
    required this.kind,
    required this.type,
    required this.ts,
    this.traceId,
    this.correlationId,
    this.sessionId,
    this.seq,
    this.payload,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory Envelope.fromJson(Map<String, Object?> json) => Envelope(
        v: json['v']! as int,
        id: json['id']! as String,
        kind: json['kind']! as String,
        type: json['type']! as String,
        ts: json['ts']! as String,
        traceId: json['traceId'] as String?,
        correlationId: json['correlationId'] as String?,
        sessionId: json['sessionId'] as String?,
        seq: json['seq'] as int?,
        payload: json['payload'] as Map<String, Object?>?,
      );

  /// Protocol version. Adding an optional field or a new event does not change it; removing a field, renaming a type or changing a meaning does.
  final int v;

  /// ULID unique to this frame.
  final String id;

  /// What the frame is. `request` travels server to client and demands an answer — that is the case the whole protocol is designed around.
  final String kind;

  /// What the frame is, within its kind.
  final String type;

  /// ISO 8601 instant, in UTC.
  final String ts;

  /// Correlates this frame with the server logs of the same operation.
  final String? traceId;

  /// `id` of the frame that caused this one.
  final String? correlationId;

  /// Session the frame belongs to, when it belongs to one. It is what fan-out routes on, and what ties the many traces of a conversation together.
  final String? sessionId;

  /// Monotonic per session, on events only. This is what makes replay after a reconnect possible.
  final int? seq;

  /// Contents, defined per `type`.
  final Map<String, Object?>? payload;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'v': v,
      'id': id,
      'kind': kind,
      'type': type,
      'ts': ts,
    };

    if (traceId != null) {
      json['traceId'] = traceId;
    }

    if (correlationId != null) {
      json['correlationId'] = correlationId;
    }

    if (sessionId != null) {
      json['sessionId'] = sessionId;
    }

    if (seq != null) {
      json['seq'] = seq;
    }

    if (payload != null) {
      json['payload'] = payload;
    }

    return json;
  }
}

/// A command was accepted — not that it finished. The outcome arrives as an event; waiting on this ack for a result reintroduces request/response where the protocol chose a stream.
class CommandAcceptedPayload {
  const CommandAcceptedPayload({
    required this.command,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory CommandAcceptedPayload.fromJson(Map<String, Object?> json) => CommandAcceptedPayload(
        command: json['command']! as String,
      );

  /// `type` of the command being acknowledged.
  final String command;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'command': command,
    };

    return json;
  }
}

/// What this server will accept, so the client does not have to discover it by being refused.
class ConnectionReadyPayloadLimits {
  const ConnectionReadyPayloadLimits({
    required this.maxFrameBytes,
    required this.replayBufferSize,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ConnectionReadyPayloadLimits.fromJson(Map<String, Object?> json) => ConnectionReadyPayloadLimits(
        maxFrameBytes: json['maxFrameBytes']! as int,
        replayBufferSize: json['replayBufferSize']! as int,
      );

  final int maxFrameBytes;

  final int replayBufferSize;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'maxFrameBytes': maxFrameBytes,
      'replayBufferSize': replayBufferSize,
    };

    return json;
  }
}

/// Answer to a successful handshake. An ack, not an event: it acknowledges the command that caused it.
class ConnectionReadyPayload {
  const ConnectionReadyPayload({
    required this.connectionId,
    required this.serverVersion,
    required this.limits,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ConnectionReadyPayload.fromJson(Map<String, Object?> json) => ConnectionReadyPayload(
        connectionId: json['connectionId']! as String,
        serverVersion: json['serverVersion']! as String,
        limits: ConnectionReadyPayloadLimits.fromJson(json['limits']! as Map<String, Object?>),
      );

  final String connectionId;

  final String serverVersion;

  /// What this server will accept, so the client does not have to discover it by being refused.
  final ConnectionReadyPayloadLimits limits;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'connectionId': connectionId,
      'serverVersion': serverVersion,
      'limits': limits.toJson(),
    };

    return json;
  }
}

/// Answer to `session.attach`. Says what was replayed and whether anything was lost.
class SessionAttachedPayload {
  const SessionAttachedPayload({
    required this.sessionId,
    required this.replayed,
    required this.oldestAvailableSeq,
    required this.gap,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionAttachedPayload.fromJson(Map<String, Object?> json) => SessionAttachedPayload(
        sessionId: json['sessionId']! as String,
        replayed: json['replayed']! as int,
        oldestAvailableSeq: json['oldestAvailableSeq']! as int,
        gap: json['gap']! as bool,
      );

  final String sessionId;

  /// How many buffered events follow this ack.
  final int replayed;

  /// Lowest `seq` still in the buffer; 0 when the buffer is empty.
  final int oldestAvailableSeq;

  /// The requested sequence had already fallen out of the buffer. The client drops its local state and reloads over HTTP — it never stitches a partial hole.
  final bool gap;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'replayed': replayed,
      'oldestAvailableSeq': oldestAvailableSeq,
      'gap': gap,
    };

    return json;
  }
}

/// Who is connecting, for diagnostics and for the deprecation window.
class ConnectionAuthenticatePayloadClient {
  const ConnectionAuthenticatePayloadClient({
    required this.kind,
    required this.version,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ConnectionAuthenticatePayloadClient.fromJson(Map<String, Object?> json) => ConnectionAuthenticatePayloadClient(
        kind: json['kind']! as String,
        version: json['version']! as String,
      );

  final String kind;

  final String version;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'kind': kind,
      'version': version,
    };

    return json;
  }
}

/// Opens the connection. Without it inside 5 seconds the server closes with 4401.
class ConnectionAuthenticatePayload {
  const ConnectionAuthenticatePayload({
    required this.token,
    required this.locale,
    required this.client,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ConnectionAuthenticatePayload.fromJson(Map<String, Object?> json) => ConnectionAuthenticatePayload(
        token: json['token']! as String,
        locale: json['locale']! as String,
        client: ConnectionAuthenticatePayloadClient.fromJson(json['client']! as Map<String, Object?>),
      );

  /// OIDC access token. In the frame body, never in the query string — a query string leaks into proxy logs.
  final String token;

  /// Language of this connection, not of the user.
  final String locale;

  /// Who is connecting, for diagnostics and for the deprecation window.
  final ConnectionAuthenticatePayloadClient client;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'token': token,
      'locale': locale,
      'client': client.toJson(),
    };

    return json;
  }
}

/// Renews the credential without reopening the socket. An access token expiring on an open connection does not drop it; failing to renew within the 60 s grace period closes it with 4401.
class ConnectionReauthenticatePayload {
  const ConnectionReauthenticatePayload({
    required this.token,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ConnectionReauthenticatePayload.fromJson(Map<String, Object?> json) => ConnectionReauthenticatePayload(
        token: json['token']! as String,
      );

  /// The renewed OIDC access token.
  final String token;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'token': token,
    };

    return json;
  }
}

/// Starts observing a session. On a reconnect it also asks for the events missed while the socket was down.
class SessionAttachPayload {
  const SessionAttachPayload({
    required this.sessionId,
    this.resumeFromSeq,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionAttachPayload.fromJson(Map<String, Object?> json) => SessionAttachPayload(
        sessionId: json['sessionId']! as String,
        resumeFromSeq: json['resumeFromSeq'] as int?,
      );

  /// Session to observe.
  final String sessionId;

  /// Highest `seq` the client already has. The server replays from the next one, or answers `gap: true` when that sequence has fallen out of the buffer.
  final int? resumeFromSeq;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
    };

    if (resumeFromSeq != null) {
      json['resumeFromSeq'] = resumeFromSeq;
    }

    return json;
  }
}

/// The vertical slice of the bootstrap: it crosses every layer without touching the Agent SDK. Omitting `sessionId` opens a session; sending one pings that session.
class SessionPingPayload {
  const SessionPingPayload({
    this.sessionId,
    required this.nonce,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionPingPayload.fromJson(Map<String, Object?> json) => SessionPingPayload(
        sessionId: json['sessionId'] as String?,
        nonce: json['nonce']! as String,
      );

  /// Session to ping. Absent opens a new one, and the pong carries the id it got.
  final String? sessionId;

  /// Echoed back in the pong, so a client can tell its own round trip from someone else's on the same session.
  final String nonce;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'nonce': nonce,
    };

    if (sessionId != null) {
      json['sessionId'] = sessionId;
    }

    return json;
  }
}

class ErrorPayloadDetailsItem {
  const ErrorPayloadDetailsItem({
    required this.field,
    required this.rule,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ErrorPayloadDetailsItem.fromJson(Map<String, Object?> json) => ErrorPayloadDetailsItem(
        field: json['field']! as String,
        rule: json['rule']! as String,
      );

  final String field;

  final String rule;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'field': field,
      'rule': rule,
    };

    return json;
  }
}

/// The error envelope, identical to the HTTP one. See docs/architecture/shared/04-errors-and-http.md.
class ErrorPayload {
  const ErrorPayload({
    required this.code,
    required this.messageKey,
    this.params,
    required this.traceId,
    this.httpEquivalent,
    this.details,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory ErrorPayload.fromJson(Map<String, Object?> json) => ErrorPayload(
        code: json['code']! as String,
        messageKey: json['messageKey']! as String,
        params: json['params'] as Map<String, Object?>?,
        traceId: json['traceId']! as String,
        httpEquivalent: json['httpEquivalent'] as int?,
        details: json['details'] == null ? null : (json['details']! as List<Object?>).map((item) => ErrorPayloadDetailsItem.fromJson(item! as Map<String, Object?>)).toList(growable: false),
      );

  /// Stable, for client logic. Changing one is a breaking change.
  final String code;

  /// For display. The client translates it — the server never sends prose.
  final String messageKey;

  /// Interpolation values for the message key.
  final Map<String, Object?>? params;

  /// Lets a user report the problem and someone find it in the log.
  final String traceId;

  /// The status this error would carry over HTTP. A WebSocket frame has no status line, and the mapping in docs/architecture/shared/04-errors-and-http.md holds on both transports.
  final int? httpEquivalent;

  /// Validation only: every invalid field, not just the first.
  final List<ErrorPayloadDetailsItem>? details;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'code': code,
      'messageKey': messageKey,
      'traceId': traceId,
    };

    if (params != null) {
      json['params'] = params;
    }

    if (httpEquivalent != null) {
      json['httpEquivalent'] = httpEquivalent;
    }

    if (details != null) {
      json['details'] = details?.map((item) => item.toJson()).toList(growable: false);
    }

    return json;
  }
}

/// Result of `session.ping`, carrying the `seq` the hub assigned. Like every event it is fanned out to every connection observing the session, not only to the one that asked.
class SessionPongPayload {
  const SessionPongPayload({
    required this.sessionId,
    required this.pingedAt,
    required this.pingCount,
    required this.nonce,
  });

  /// Reads a decoded JSON map. Unknown keys are ignored, never rejected.
  factory SessionPongPayload.fromJson(Map<String, Object?> json) => SessionPongPayload(
        sessionId: json['sessionId']! as String,
        pingedAt: json['pingedAt']! as String,
        pingCount: json['pingCount']! as int,
        nonce: json['nonce']! as String,
      );

  final String sessionId;

  /// ISO 8601 instant in UTC, read from the server clock.
  final String pingedAt;

  /// How many times this session has been pinged, counting this one.
  final int pingCount;

  /// Echo of the nonce the command carried.
  final String nonce;

  /// A JSON map with the absent optional fields left out.
  Map<String, Object?> toJson() {
    final Map<String, Object?> json = <String, Object?>{
      'sessionId': sessionId,
      'pingedAt': pingedAt,
      'pingCount': pingCount,
      'nonce': nonce,
    };

    return json;
  }
}
